#!/usr/bin/env python3
"""Chapter 06 (wavefunction): checked numbers and the generated figure.

    python3 scripts/ch06_wavefunction.py            # print the numbers used in the essay
    python3 scripts/ch06_wavefunction.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:packet
markers in chapters/06-wavefunction.html.

FIGURE RECORD
  Drawn            : a Gaussian wave packet at one instant,
                       psi(x) = exp(-x^2 / (4 sigma^2)) * exp(i k0 x)   (unnormalised)
  Curves           : Re psi (thin, oscillating) and |psi|^2 (thick, smooth), both on
                     the same vertical scale, where |psi|^2 = 1 at the centre
  Horizontal axis  : x in units of sigma, -4 to 4
  Parameters       : k0 sigma = 8  (about 10 wavelengths across the plotted range)
"""
import math
import re
import sys
from pathlib import Path

h = 6.62607015e-34
hbar = h / (2 * math.pi)
m_e = 9.1093837015e-31


def report():
    # worked example: psi = A exp(-|x|/b)
    b = 0.1e-9
    A2 = 1 / b
    print(f"psi = A exp(-|x|/b): integral of |psi|^2 = A^2 b  ->  A = 1/sqrt(b) = {math.sqrt(A2):.4e} m^-1/2 for b = 0.1 nm")
    print(f"P(|x| < b)  = 1 - e^-2 = {1-math.exp(-2):.4f}")
    print(f"P(0 < x < b) = (1 - e^-2)/2 = {(1-math.exp(-2))/2:.4f}")
    print(f"P(|x| > 2b) = e^-4 = {math.exp(-4):.4f}   (using psi instead of |psi|^2 would give e^-2 = {math.exp(-2):.4f})")
    w = 0.001e-9
    print(f"window 0.001 nm at x=0: P ~ |psi(0)|^2 w = {A2*w:.4f}; at x=b: {A2*math.exp(-2)*w:.5f}; ratio e^-2 = {math.exp(-2):.4f}")
    print()
    # Gaussian spreading, sigma(t) = sigma0 sqrt(1 + (t/tau)^2), tau = 2 m sigma0^2 / hbar
    for name, m, s0 in (("electron, 1 nm", m_e, 1e-9), ("electron, 0.1 nm", m_e, 1e-10),
                        ("dust grain 1 ug, 1 um", 1e-9, 1e-6)):
        tau = 2 * m * s0**2 / hbar
        print(f"{name}: tau = {tau:.3e} s = {tau/3.156e7:.3e} yr")
        for t in (1e-12, 1e-9, 1.0):
            print(f"   t = {t:g} s: width = {s0*math.sqrt(1+(t/tau)**2):.3e} m")


# ---------------------------------------------------------------- figure
W, H = 680, 330
LM, RM, TOP, BOT = 30, 20, 20, 50
K0 = 8.0


def sx(u):
    return LM + (W - LM - RM) * (u + 4) / 8


def sy(v):
    mid = TOP + (H - TOP - BOT) / 2
    return mid - (H - TOP - BOT) / 2 * v / 1.1


def path(fn, n=800):
    pts = []
    for i in range(n + 1):
        u = -4 + 8 * i / n
        pts.append(f"{sx(u):.1f},{sy(fn(u)):.1f}")
    return "M" + " L".join(pts)


def figure_svg():
    env = lambda u: math.exp(-u * u / 4)
    re_psi = lambda u: env(u) * math.cos(K0 * u)
    dens = lambda u: env(u) ** 2
    o = []
    a = o.append
    a(f'<svg class="fig-svg" viewBox="0 0 {W} {H}" role="img" aria-labelledby="fig-packet-title fig-packet-desc">')
    a('<title id="fig-packet-title">A wave packet: the wavefunction and its probability density</title>')
    a('<desc id="fig-packet-desc">A thin curve oscillates rapidly between positive and negative values inside a bell-shaped envelope: the real part of the wavefunction. A thick smooth bell curve, always positive and without oscillations, is the probability density.</desc>')
    a(f'<path class="fig-axis" d="M{LM},{sy(0):.1f} H{W-RM}"/>')
    for u in range(-4, 5, 2):
        a(f'<path class="fig-axis" d="M{sx(u):.1f},{sy(0):.1f} v5"/>')
    a(f'<text class="fig-tick" x="{sx(0):.1f}" y="{sy(0)+20:.1f}" text-anchor="middle">centre</text>')
    a(f'<path class="fig-axis" style="stroke-dasharray:3 4" d="M{sx(-2):.1f},{sy(-1.05):.1f} v10 M{sx(2):.1f},{sy(-1.05):.1f} v10 M{sx(-2):.1f},{sy(-1.05)+5:.1f} H{sx(2):.1f}"/>')
    a(f'<text class="fig-note" x="{sx(0):.1f}" y="{sy(-1.05)+22:.1f}" text-anchor="middle">most of the probability lies in this range</text>')
    a(f'<path class="fig-curve fig-mid" style="stroke-width:1.2" d="{path(re_psi)}"/>')
    a(f'<path class="fig-curve fig-hot" style="stroke-width:3" d="{path(dens)}"/>')
    a(f'<text class="fig-note" x="{sx(1.2):.1f}" y="{sy(0.95):.1f}">|ψ|², the probability density</text>')
    a(f'<text class="fig-note" x="{sx(-3.9):.1f}" y="{sy(0.62):.1f}">real part of ψ:</text>')
    a(f'<text class="fig-note" x="{sx(-3.9):.1f}" y="{sy(0.62)+16:.1f}">oscillates, can be negative</text>')
    a(f'<text class="fig-label" x="{W-RM:.1f}" y="{sy(0)-8:.1f}" text-anchor="end">x</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "06-wavefunction.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:packet generated by scripts/ch06_wavefunction.py -->\n" + figure_svg() + "\n<!-- /FIGURE:packet -->"
    new, n = re.subn(r"<!-- FIGURE:packet.*?<!-- /FIGURE:packet -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:packet markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
