#!/usr/bin/env python3
"""Chapter 09c (angular momentum): checked numbers and the generated figure.

    python3 scripts/ch09c_angular.py            # print the numbers used in the essay
    python3 scripts/ch09c_angular.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:vector
markers in chapters/09c-angular-momentum.html.

FIGURE RECORD
  Drawn   : the "vector model" for l = 2. A semicircle of radius sqrt(l(l+1)) = sqrt 6 = 2.449
            (units of hbar) and the five allowed z-components m = -2..2, each shown as an arrow of
            length sqrt 6 whose tip lies at height m. Axis ticks at integer multiples of hbar.
Data    : 12C16O J = 1 -> 0 line 115.2712 GHz; J = 2 -> 1 230.5380 GHz; J = 3 -> 2 345.7960 GHz;
          13C16O J = 1 -> 0 110.2014 GHz (laboratory values).
"""
import math
import re
import sys
from pathlib import Path

h = 6.62607015e-34
hbar = h / (2 * math.pi)
eV = 1.602176634e-19
u = 1.66053906660e-27


def report():
    nu10 = 115.2712e9
    B = h * nu10 / 2            # hbar^2 / 2I, joules
    I = hbar**2 / (2 * B)
    mu = 12.000 * 15.995 / (12.000 + 15.995) * u
    r = math.sqrt(I / mu)
    print(f"hbar^2/2I = h nu/2 = {B/eV:.4e} eV; I = {I:.4e} kg m^2; bond length = {r*1e12:.1f} pm")
    for l in range(0, 4):
        print(f"   level l = {l}: E = l(l+1) hbar^2/2I = {l*(l+1)*B/eV*1e3:.4f} meV; |L| = sqrt(l(l+1)) hbar = {math.sqrt(l*(l+1)):.3f} hbar")
    for l, meas in ((1, 230.5380), (2, 345.7960)):
        print(f"   predicted {l+1}->{l}: {(l+1)*nu10/1e9:.3f} GHz, measured {meas} GHz")
    mu13 = 13.003 * 15.995 / (13.003 + 15.995) * u
    print(f"13CO predicted 1->0: {nu10*mu/mu13/1e9:.2f} GHz (measured 110.20); naive 12/13 scaling: {nu10*12/13/1e9:.2f} GHz")
    print(f"mu 12CO = {mu/u:.3f} u, 13CO = {mu13/u:.3f} u")
    Ltop = 0.01
    print(f"a top with L = {Ltop} J s has l ~ L/hbar = {Ltop/hbar:.1e}")
    print(f"photon wavelength of 115.27 GHz = {299792458/nu10*1e3:.2f} mm")


# ---------------------------------------------------------------- figure
W, H = 680, 360


def figure_svg():
    o = []
    a = o.append
    l = 2
    R = math.sqrt(l * (l + 1))
    cx, cy, s = 250, 180, 58
    a(f'<svg class="fig-svg" viewBox="0 0 {W} {H}" role="img" aria-labelledby="fig-vec-title fig-vec-desc">')
    a('<title id="fig-vec-title">The allowed orientations of angular momentum for l = 2</title>')
    a('<desc id="fig-vec-desc">A vertical z axis with ticks at minus 2 to plus 2 units of h-bar. Five arrows of equal length, the square root of 6 units, radiate from the origin, their tips on a semicircle at heights minus 2, minus 1, 0, 1 and 2. Even the highest arrow leans away from the axis.</desc>')
    a(f'<path class="fig-axis" style="stroke-width:1.4" d="M{cx},{cy+s*2.9:.1f} V{cy-s*2.9:.1f}"/>')
    a(f'<text class="fig-label" x="{cx+8}" y="{cy-s*2.75:.1f}">z</text>')
    pts = " L".join(f"{cx+s*R*math.sin(t):.1f},{cy-s*R*math.cos(t):.1f}" for t in [math.pi * i / 100 for i in range(101)])
    a(f'<path class="fig-axis" style="stroke-dasharray:4 4" d="M{pts}"/>')
    for m in range(-l, l + 1):
        y = cy - s * m
        xt = cx + s * math.sqrt(R * R - m * m)
        a(f'<path class="fig-axis" style="stroke-dasharray:2 3" d="M{cx-6},{y:.1f} H{xt:.1f}"/>')
        a(f'<text class="fig-tick" x="{cx-12}" y="{y+4:.1f}" text-anchor="end">m = {m:+d}</text>'.replace("+0", "0"))
        a(f'<path class="fig-curve fig-hot" style="stroke-width:2.2" d="M{cx},{cy} L{xt:.1f},{y:.1f}"/>')
        a(f'<circle cx="{xt:.1f}" cy="{y:.1f}" r="3.5" class="fig-dot"/>')
    tx = 440
    a(f'<text class="fig-note" x="{tx}" y="120">length of every arrow:</text>')
    a(f'<text class="fig-note" x="{tx}" y="138">√(l(l+1)) ħ = √6 ħ ≈ 2.45 ħ</text>')
    a(f'<text class="fig-note" x="{tx}" y="176">largest z-component:</text>')
    a(f'<text class="fig-note" x="{tx}" y="194">l ħ = 2 ħ</text>')
    a(f'<text class="fig-note" x="{tx}" y="232">so no arrow lies</text>')
    a(f'<text class="fig-note" x="{tx}" y="250">exactly along z</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "09c-angular-momentum.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:vector generated by scripts/ch09c_angular.py -->\n" + figure_svg() + "\n<!-- /FIGURE:vector -->"
    new, n = re.subn(r"<!-- FIGURE:vector.*?<!-- /FIGURE:vector -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:vector markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
