#!/usr/bin/env python3
"""Chapter 11 (spin): checked numbers and the generated figure.

    python3 scripts/ch11_spin.py            # print the numbers used in the essay
    python3 scripts/ch11_spin.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:angles markers
in chapters/11-spin.html.

FIGURE RECORD
  Plotted quantity : probability that a system prepared "up" (spin) or "horizontal" (photon)
                     passes an analyser turned by angle theta
                       spin-1/2 : cos^2(theta/2)   (solid)
                       photon   : cos^2(theta)     (dashed)
  Horizontal axis  : analyser angle theta, 0 to 360 degrees
Stern-Gerlach numbers: illustrative values close to the 1922 apparatus (oven ~1300 K silver beam,
field gradient ~10 T/cm over ~3.5 cm); the essay quotes only the order of magnitude.
"""
import cmath
import math
import re
import sys
from pathlib import Path

muB = 9.2740100783e-24
amu = 1.66053906660e-27
kB = 1.380649e-23


def report():
    m_ag = 107.87 * amu
    grad = 1000.0            # T/m (10 T/cm)
    F = muB * grad
    a = F / m_ag
    v = 550.0                # m/s, typical beam speed
    L = 0.035
    t = L / v
    d = 0.5 * a * t * t
    print(f"force = {F:.2e} N, acceleration = {a:.2e} m/s^2, time in magnet = {t:.2e} s, deflection = {d*1e3:.3f} mm each way")
    print(f"thermal speed scale sqrt(3kT/m) at 1300 K = {math.sqrt(3*kB*1300/m_ag):.0f} m/s")
    # spin rotation matrices
    def up_along(theta):
        return (math.cos(theta / 2), math.sin(theta / 2))
    for deg in (0, 60, 90, 120, 180, 360):
        th = math.radians(deg)
        amp = up_along(th)[0]
        print(f"analyser at {deg:3d} deg: spin P(up) = cos^2(t/2) = {amp**2:.3f}; photon P = cos^2 t = {math.cos(th)**2:.3f};"
              f" <S_theta>/(hbar/2) for z-up = {math.cos(th):+.3f}")
    # 2 pi rotation: R(theta) = exp(-i theta sigma_z / 2) applied to (1,1)/sqrt2
    for deg in (360, 720):
        th = math.radians(deg)
        print(f"rotation by {deg} deg multiplies spin-up by e^(-i t/2) = {cmath.exp(-1j*th/2):.3f}")
    # sequential: z+ -> x+ -> z-
    print(f"z+ then x+ then z-: {0.5*0.5:.2f} of the atoms leaving the first filter")
    # Pauli matrices check
    sx = ((0, 1), (1, 0)); sy = ((0, -1j), (1j, 0)); sz = ((1, 0), (0, -1))
    mm = lambda X, Y: tuple(tuple(sum(X[i][k] * Y[k][j] for k in range(2)) for j in range(2)) for i in range(2))
    comm = tuple(tuple(mm(sx, sy)[i][j] - mm(sy, sx)[i][j] for j in range(2)) for i in range(2))
    print("[sx, sy] =", comm, "= 2i sz")


W, H = 680, 320
L_, R_, T_, B_ = 60, 20, 20, 50


def sx(d):
    return L_ + (W - L_ - R_) * d / 360


def sy(p):
    return H - B_ - (H - T_ - B_) * p / 1.08


def figure_svg():
    o = []
    a = o.append
    a(f'<svg class="fig-svg" viewBox="0 0 {W} {H}" role="img" aria-labelledby="fig-ang-title fig-ang-desc">')
    a('<title id="fig-ang-title">Passing probability against analyser angle, for spin and for photon polarisation</title>')
    a('<desc id="fig-ang-desc">Two curves over a full turn of the analyser. The solid spin curve falls from 1 at zero degrees to 0 at 180 degrees and back to 1 at 360. The dashed photon curve falls to 0 already at 90 degrees, returns to 1 at 180, and repeats.</desc>')
    a(f'<path class="fig-axis" d="M{L_},{T_} V{H-B_} H{W-R_}"/>')
    for d in range(0, 361, 90):
        a(f'<path class="fig-axis" d="M{sx(d):.1f},{H-B_} v5"/>')
        a(f'<text class="fig-tick" x="{sx(d):.1f}" y="{H-B_+19}" text-anchor="middle">{d}°</text>')
    for p in (0, 0.5, 1.0):
        a(f'<path class="fig-axis" d="M{L_},{sy(p):.1f} h-5"/>')
        a(f'<text class="fig-tick" x="{L_-9}" y="{sy(p)+4:.1f}" text-anchor="end">{p:g}</text>')
    a(f'<text class="fig-label" x="{(L_+W-R_)/2:.1f}" y="{H-12}" text-anchor="middle">angle of the analyser from the preparation direction</text>')
    a(f'<text class="fig-label" transform="translate(18,{(T_+H-B_)/2:.1f}) rotate(-90)" text-anchor="middle">probability of passing</text>')
    spin = " L".join(f"{sx(d):.1f},{sy(math.cos(math.radians(d)/2)**2):.1f}" for d in [i * 0.5 for i in range(721)])
    phot = " L".join(f"{sx(d):.1f},{sy(math.cos(math.radians(d))**2):.1f}" for d in [i * 0.5 for i in range(721)])
    a(f'<path class="fig-curve fig-hot" style="stroke-width:2.6" d="M{spin}"/>')
    a(f'<path class="fig-curve fig-classical" d="M{phot}"/>')
    a(f'<text class="fig-note" x="{sx(196):.1f}" y="{sy(0.08):.1f}">spin: cos²(θ/2), opposite at 180°</text>')
    a(f'<text class="fig-note" x="{sx(98):.1f}" y="{sy(0.03):.1f}">photon: cos²θ</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "11-spin.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:angles generated by scripts/ch11_spin.py -->\n" + figure_svg() + "\n<!-- /FIGURE:angles -->"
    new, n = re.subn(r"<!-- FIGURE:angles.*?<!-- /FIGURE:angles -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:angles markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
