#!/usr/bin/env python3
"""Chapter 12 (identical particles): checked numbers and the generated figure.

    python3 scripts/ch12_identical.py            # print the numbers used in the essay
    python3 scripts/ch12_identical.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:exchange
markers in chapters/12-identical-particles.html.

FIGURE RECORD
  System           : two non-interacting particles in a 1-D box of width L, one in the box state
                     n = 1 and one in n = 2 (spatial part only)
  Plotted quantity : probability density of the separation s = |x1 - x2|, in units of 1/L,
                     for three cases: distinguishable (product state), symmetric (+) and
                     antisymmetric (-) combinations; each integrates to 1 over 0 < s < L
  Horizontal axis  : s / L from 0 to 1
Ionisation energies (eV, NIST): H 13.60, He 24.59, Li 5.39, Be 9.32, Ne 21.56, Na 5.14.
"""
import math
import re
import sys
from pathlib import Path

N = 400


def phi(n, x):
    return math.sqrt(2) * math.sin(n * math.pi * x)


def sep_density(kind, bins=100):
    """Density of s = |x1 - x2| at bin centres, by direct integration:
    p(s) = integral over x of [f(x, x+s) + f(x+s, x)] for 0 < x < 1 - s."""
    def f(x1, x2):
        a = phi(1, x1) * phi(2, x2)
        b = phi(1, x2) * phi(2, x1)
        if kind == "dist":
            return a * a
        if kind == "sym":
            return (a + b) ** 2 / 2
        return (a - b) ** 2 / 2
    out = []
    for k in range(bins):
        sv = (k + 0.5) / bins
        m = N
        dx = (1 - sv) / m
        out.append(sum(f(x, x + sv) + f(x + sv, x) for x in [(i + 0.5) * dx for i in range(m)]) * dx)
    return out


def report():
    for kind in ("dist", "sym", "anti"):
        d = sep_density(kind)
        total = sum(d) / len(d)
        close = sum(d[:10]) / len(d)
        mean = sum((k + 0.5) / len(d) * d[k] for k in range(len(d))) / len(d)
        print(f"{kind:5s}: total = {total:.4f}, P(s < 0.1 L) = {close:.4f}, <s> = {mean:.3f} L")
    ie = {"H": 13.60, "He": 24.59, "Li": 5.39, "Be": 9.32, "Ne": 21.56, "Na": 5.14}
    print("ionisation energies:", ie)
    print("states per level with spin, 2 n^2:", [2 * n * n for n in (1, 2, 3, 4)])


W, H = 680, 320
L_, R_, T_, B_ = 60, 20, 20, 50
YM = 4.0


def sx(s):
    return L_ + (W - L_ - R_) * s


def sy(p):
    return H - B_ - (H - T_ - B_) * p / YM


def figure_svg():
    o = []
    a = o.append
    a(f'<svg class="fig-svg" viewBox="0 0 {W} {H}" role="img" aria-labelledby="fig-ex-title fig-ex-desc">')
    a('<title id="fig-ex-title">How far apart two particles are found, for symmetric and antisymmetric states</title>')
    a('<desc id="fig-ex-desc">Probability density of the separation between two particles in a box, one in the lowest state and one in the next. The antisymmetric curve starts at zero at zero separation: the particles are never found together. The symmetric curve is highest at zero separation. The distinguishable case lies between.</desc>')
    a(f'<path class="fig-axis" d="M{L_},{T_} V{H-B_} H{W-R_}"/>')
    for s in (0, 0.25, 0.5, 0.75, 1.0):
        a(f'<path class="fig-axis" d="M{sx(s):.1f},{H-B_} v5"/>')
        a(f'<text class="fig-tick" x="{sx(s):.1f}" y="{H-B_+19}" text-anchor="middle">{s:g}</text>')
    for p in (0, 1, 2, 3, 4):
        a(f'<path class="fig-axis" d="M{L_},{sy(p):.1f} h-5"/>')
        a(f'<text class="fig-tick" x="{L_-9}" y="{sy(p)+4:.1f}" text-anchor="end">{p}</text>')
    a(f'<text class="fig-label" x="{(L_+W-R_)/2:.1f}" y="{H-12}" text-anchor="middle">separation of the two particles, as a fraction of the box width</text>')
    a(f'<text class="fig-label" transform="translate(18,{(T_+H-B_)/2:.1f}) rotate(-90)" text-anchor="middle">probability density</text>')
    for kind, cls, extra in (("dist", "fig-cool", ""), ("sym", "fig-mid", ' style="stroke-dasharray:6 4"'), ("anti", "fig-hot", ' style="stroke-width:2.6"')):
        d = sep_density(kind)
        pts = " L".join(f"{sx((k+0.5)/len(d)):.1f},{sy(v):.1f}" for k, v in enumerate(d))
        a(f'<path class="fig-curve {cls}"{extra} d="M{pts}"/>')
    a(f'<text class="fig-note" x="{sx(0.13):.1f}" y="{sy(3.75):.1f}">symmetric (dashed): often together</text>')
    a(f'<text class="fig-note" x="{sx(0.07):.1f}" y="{sy(1.62):.1f}">distinguishable</text>')
    a(f'<text class="fig-note" x="{sx(0.45):.1f}" y="{sy(2.6):.1f}">antisymmetric</text>')
    a(f'<text class="fig-note" x="{sx(0.012):.1f}" y="{sy(0.25):.1f}">← never together</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "12-identical-particles.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:exchange generated by scripts/ch12_identical.py -->\n" + figure_svg() + "\n<!-- /FIGURE:exchange -->"
    new, n = re.subn(r"<!-- FIGURE:exchange.*?<!-- /FIGURE:exchange -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:exchange markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
