#!/usr/bin/env python3
"""Chapter 13 (approximations): checked numbers and the generated figure.

    python3 scripts/ch13_approximations.py            # print the numbers used in the essay
    python3 scripts/ch13_approximations.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:perturb
markers in chapters/13-approximations.html.

FIGURE RECORD
  Model            : two levels 0 and Delta, coupled by an off-diagonal element u:
                     H = [[0, u], [u, Delta]]
  Plotted quantity : shift of the lower level, in units of Delta, against u / Delta (0 to 1)
                       exact          : 1/2 - sqrt(1/4 + (u/Delta)^2)        (solid)
                       second order   : -(u/Delta)^2                          (dashed)
Helium: E_H = 13.606 eV (hydrogen ground-state binding); measured total binding 79.0 eV
(24.59 + 54.42 eV, the two ionisation energies).
"""
import math
import re
import sys
from pathlib import Path

EH = 13.6057


def report():
    Z = 2
    E0 = -2 * Z * Z * EH
    W = 1.25 * Z * EH           # (5/8) Z * 2 EH
    print(f"helium zeroth order {E0:.1f} eV; first-order repulsion <W> = (5/4) Z E_H = {W:.1f} eV; total {E0+W:.1f} eV")
    Zp = Z - 5 / 16
    Evar = -2 * EH * Zp * Zp
    print(f"variational Z' = {Zp:.4f}; E = -2 E_H Z'^2 = {Evar:.2f} eV")
    meas = 24.587 + 54.418
    print(f"measured total = {meas:.1f} eV; first-order error {100*(E0+W+meas)/meas:.1f}%; variational error {100*(Evar+meas)/meas:.1f}%")
    for Zt in (1.5, 1.6875, 1.8, 2.0):
        print(f"   E(Z'={Zt}) = {2*EH*(Zt*Zt - 2*Z*Zt + 5/8*Zt):.2f} eV")
    print()
    for r in (0.1, 0.3, 0.5, 1.0, 2.0):
        exact = 0.5 - math.sqrt(0.25 + r * r)
        pert = -r * r
        print(f"u/Delta = {r}: exact shift = {exact:.4f} Delta, second order = {pert:.4f} Delta, error = {100*(pert-exact)/exact:.1f}%")
    for d in (1.0, 0.1, 0.01, 0.0):
        u = 0.1
        ex = d / 2 - math.sqrt(d * d / 4 + u * u)
        pt = -u * u / d if d else float("-inf")
        print(f"u = 0.1, Delta = {d}: exact {ex:.4f}, second order {pt:.4f}")


W_, H_ = 680, 320
L_, R_, T_, B_ = 70, 20, 20, 50
YM = -1.05


def sx(r):
    return L_ + (W_ - L_ - R_) * r


def sy(e):
    return T_ + (H_ - T_ - B_) * e / YM


def figure_svg():
    o = []
    a = o.append
    a(f'<svg class="fig-svg" viewBox="0 0 {W_} {H_}" role="img" aria-labelledby="fig-pt-title fig-pt-desc">')
    a('<title id="fig-pt-title">Exact and second-order energy shift of a coupled two-level system</title>')
    a('<desc id="fig-pt-desc">The downward shift of the lower level as the coupling grows from zero to the level spacing. The exact and approximate curves agree closely for small coupling and separate beyond about a third of the spacing; at a coupling equal to the spacing the approximation overshoots by more than half.</desc>')
    a(f'<path class="fig-axis" d="M{L_},{T_} V{H_-B_} H{W_-R_}"/>')
    a(f'<path class="fig-axis" style="stroke-dasharray:3 4" d="M{L_},{sy(0):.1f} H{W_-R_}"/>')
    for r in (0, 0.25, 0.5, 0.75, 1.0):
        a(f'<path class="fig-axis" d="M{sx(r):.1f},{H_-B_} v5"/>')
        a(f'<text class="fig-tick" x="{sx(r):.1f}" y="{H_-B_+19}" text-anchor="middle">{r:g}</text>')
    for e in (0, -0.25, -0.5, -0.75, -1.0):
        a(f'<path class="fig-axis" d="M{L_},{sy(e):.1f} h-5"/>')
        a(f'<text class="fig-tick" x="{L_-9}" y="{sy(e)+4:.1f}" text-anchor="end">{e:g}</text>')
    a(f'<text class="fig-label" x="{(L_+W_-R_)/2:.1f}" y="{H_-12}" text-anchor="middle">coupling u, as a fraction of the level spacing Δ</text>')
    a(f'<text class="fig-label" transform="translate(18,{(T_+H_-B_)/2:.1f}) rotate(-90)" text-anchor="middle">shift of the lower level (units of Δ)</text>')
    rs = [i / 400 for i in range(401)]
    ex = " L".join(f"{sx(r):.1f},{sy(0.5-math.sqrt(0.25+r*r)):.1f}" for r in rs)
    pt = " L".join(f"{sx(r):.1f},{sy(-r*r):.1f}" for r in rs)
    a(f'<path class="fig-curve fig-hot" style="stroke-width:2.6" d="M{ex}"/>')
    a(f'<path class="fig-curve fig-classical" d="M{pt}"/>')
    a(f'<text class="fig-note" x="{sx(0.72):.1f}" y="{sy(-0.30):.1f}">exact</text>')
    a(f'<text class="fig-note" x="{sx(0.55):.1f}" y="{sy(-0.62):.1f}">second order, −u²/Δ</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "13-approximations.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:perturb generated by scripts/ch13_approximations.py -->\n" + figure_svg() + "\n<!-- /FIGURE:perturb -->"
    new, n = re.subn(r"<!-- FIGURE:perturb.*?<!-- /FIGURE:perturb -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:perturb markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
