#!/usr/bin/env python3
"""Chapter 14 (measurement): checked numbers and the generated figure.

    python3 scripts/ch14_measurement.py            # print the numbers used in the essay
    python3 scripts/ch14_measurement.py --write    # also regenerate the figure in the chapter

Pure standard library. --write replaces what sits between the FIGURE:visibility
markers in chapters/14-measurement.html.

Model: spin prepared up along x, i.e. (|up> + |down>)/sqrt2 along z. A detector of N particles,
each of which ends in state |a_up> or |a_down> with overlap g = <a_down|a_up> (real, 0 < g <= 1).
Total detector overlap gamma = g^N. Afterwards the spin is measured along x:
    P(x-up) = 1/2 (1 + gamma).

FIGURE RECORD
  Plotted quantity : P(x-up) after the detector has acted, against the number of detector
                     particles N (0 to 60), for per-particle overlaps g = 0.99, 0.9 and 0.5
  Reference lines  : 1 (no record: full interference) and 1/2 (complete record)
Air collisions on a dust grain: n = 2.5e25 m^-3, mean speed 470 m/s, flux n v/4, radius 1 um.
"""
import math
import re
import sys
from pathlib import Path


def p_xup(gamma):
    return 0.5 * (1 + gamma)


def report():
    for g in (0.99, 0.9, 0.5):
        for N in (1, 10, 100, 1000):
            gam = g ** N
            print(f"g = {g}, N = {N:5d}: gamma = {gam:.3e}, P(x-up) = {p_xup(gam):.6f}")
    print(f"gamma = 0.6: P(x-up) = {p_xup(0.6):.2f}")
    n, v, r = 2.5e25, 470.0, 1e-6
    rate = n * v / 4 * 4 * math.pi * r * r
    print(f"air molecules striking a 1 um-radius grain: {rate:.1e} per second")
    lam = 6.62607015e-34 / (4.65e-26 * 470)
    print(f"de Broglie wavelength of an N2 molecule at 470 m/s: {lam*1e9:.4f} nm")


W, H = 680, 320
L_, R_, T_, B_ = 60, 20, 20, 50
NM = 60


def sx(n):
    return L_ + (W - L_ - R_) * n / NM


def sy(p):
    return H - B_ - (H - T_ - B_) * (p - 0.4) / 0.65


def figure_svg():
    o = []
    a = o.append
    a(f'<svg class="fig-svg" viewBox="0 0 {W} {H}" role="img" aria-labelledby="fig-vis-title fig-vis-desc">')
    a('<title id="fig-vis-title">Interference surviving a detector made of more and more particles</title>')
    a('<desc id="fig-vis-desc">The probability of finding the spin up along x after a detector has acted, against the number of particles in the detector. It starts at 1 and falls towards one half. With a strong record per particle it reaches one half within a few particles; with a weak record of 0.99 per particle it falls more slowly but steadily.</desc>')
    a(f'<path class="fig-axis" d="M{L_},{T_} V{H-B_} H{W-R_}"/>')
    for n in range(0, NM + 1, 10):
        a(f'<path class="fig-axis" d="M{sx(n):.1f},{H-B_} v5"/>')
        a(f'<text class="fig-tick" x="{sx(n):.1f}" y="{H-B_+19}" text-anchor="middle">{n}</text>')
    for p in (0.5, 0.75, 1.0):
        a(f'<path class="fig-axis" d="M{L_},{sy(p):.1f} h-5"/>')
        a(f'<text class="fig-tick" x="{L_-9}" y="{sy(p)+4:.1f}" text-anchor="end">{p:g}</text>')
        if p in (0.5, 1.0):
            a(f'<path class="fig-axis" style="stroke-dasharray:3 4" d="M{L_},{sy(p):.1f} H{W-R_}"/>')
    a(f'<text class="fig-label" x="{(L_+W-R_)/2:.1f}" y="{H-12}" text-anchor="middle">number of detector particles N</text>')
    a(f'<text class="fig-label" transform="translate(18,{(T_+H-B_)/2:.1f}) rotate(-90)" text-anchor="middle">P(up along x) afterwards</text>')
    for g, cls, lab, pos in ((0.99, "fig-hot", "per-particle overlap 0.99", (38, 0.87)), (0.9, "fig-mid", "0.9", (11, 0.72)),
                             (0.5, "fig-cool", "0.5", (3.2, 0.55))):
        pts = " L".join(f"{sx(n):.1f},{sy(p_xup(g**n)):.1f}" for n in [i * 0.1 for i in range(NM * 10 + 1)])
        a(f'<path class="fig-curve {cls}" d="M{pts}"/>')
        a(f'<text class="fig-note" x="{sx(pos[0]):.1f}" y="{sy(pos[1]):.1f}">{lab}</text>')
    a(f'<text class="fig-tick" x="{W-R_}" y="{sy(1.0)-6:.1f}" text-anchor="end">no record: full interference</text>')
    a(f'<text class="fig-tick" x="{W-R_}" y="{sy(0.5)-6:.1f}" text-anchor="end">complete record: ½</text>')
    a('</svg>')
    return "\n".join(o)


def write_figure():
    page = Path(__file__).resolve().parent.parent / "chapters" / "14-measurement.html"
    html = page.read_text(encoding="utf-8")
    block = "<!-- FIGURE:visibility generated by scripts/ch14_measurement.py -->\n" + figure_svg() + "\n<!-- /FIGURE:visibility -->"
    new, n = re.subn(r"<!-- FIGURE:visibility.*?<!-- /FIGURE:visibility -->", lambda m: block, html, flags=re.S)
    if n != 1:
        sys.exit("FIGURE:visibility markers not found exactly once in the chapter")
    page.write_text(new, encoding="utf-8")
    print(f"figure written into {page}")


if __name__ == "__main__":
    report()
    if "--write" in sys.argv:
        write_figure()
